credentials:
  usernames:
    alice:
      email: alice@fake.edu
      name: alice
      password: abc
    alim:
      email: alim@ucsb.edu
      name: alim
      password: abc
    josh:
      email: josh
      name: josh
      password: josh
